#!/usr/bin/env python3
# Mover Node
# RKS

# Project imports

# Python imports
import sys

# 3rd-party imports
import rospy 
import moveit_commander

class Mover:
    """
    SERVICES:
        + reset 

        + step 

        + follow

    BROADCAST:
        + static world -> odom ~ a rotation operation by theta_0, the initial heading
        of the turtle. 
    
    PARAMS:
        + list(x,y,z) waypoints ~ a list of 3D waypoints 
    """
    def __init__(self):
        """
        """
        


# Main execution loop
if __name__ == "__main__":
    try:
        mover_node = Mover()
    #If something kills this node, have it die
    except rospy.ROSInterruptException:
        pass
