# Request for arm_move/reset service to alter the pose of the realsense box.
# If xyz and roll, pitch, yaw are zero, only the clear bool will be considered
# If z is set to 0, assumed the box should be adjusted to appear on platform
#   -To prevent this, set z close to zero.
float64 x     # New x position of box
float64 y     # New y position of box
float64 z     # New z position of box
float64 roll  # New roll orientation of box
float64 pitch # New pitch orientation of box
float64 yaw   # New yaw orientation of box
bool clear    # True, if the waypoints on list should be cleared
---
# Response: Empty Response